wandb:
  project: seal_scent
  entity: danieltlevy
  mode: online

training:
  lr: 1e-4
  weight_decay: 5e-4
  epochs: 1000
  val_every: 1
  debug: False
  overfit: 0
  weighted_loss: True

model:
  h_feats: 32
  hidden_dim: 100
  K: 20
  lam: 0.01
  shared_gnn: True
  gnn_layers: 3
  gnn_mlp_layers: 2
  energy_global_dim: 128
  energy_global_local: 1
  use_energy: True


dataset:
  frac_train: 0.7
  frac_val: 0.1
  batch_size: 128
