wandb:
  project: seal_scent
  entity: danieltlevy
  mode: online
  name: null

training:
  lr: 1e-4
  weight_decay: 5e-4
  epochs: 1000
  val_every: 1
  debug: False
  overfit: 0
  weighted_loss: True
  save_checkpoint: True
  early_stopping: 100
  seed: 0

model:
  h_feats: 256
  hidden_dim: 256
  K: 20
  lam: 0.01
  shared_gnn: False
  gnn_layers: 4
  gnn_mlp_layers: 2
  energy_global_dim: 256
  energy_global_local: 1
  use_energy: True


dataset:
  frac_train: 0.7
  frac_val: 0.1
  batch_size: 128
